language: node_js
node_js:
  - "10.16.0"

branches:
  only:
    - master

before_install:
  - npm install gulp -g

script:
  - npm install
  - cd ./test/buildtool
  - gulp
  - cd ../../

cache:
  directories:
  - node_modules

notifications:
  email:
    - haofefe@163.com